project = 'LuaLoL'
description = 'League of Legends API Lua Libraries 0.1'
full_description = 'The documentation is available @{01-introduction.md|here}.'
title = 'LuaLoL Documentation'
dir = 'api'
style = '!fixed'
use_markdown_titles = true
topics = 'manual'
examples = {'../examples'}
package = '..'
format = 'markdown'
sort_modules=true
file = '../src/lol'
kind_names={topic='Manual',module='Libraries'}
custom_tags={{'remark',title='Remarks'}}
